import type { FileRiskEntry } from "@/types/analytics.types";

/**
 * Generates real, GitHub-syntax CODEOWNERS content from already-computed
 * per-file risk data — no new analysis, no AI, no extra API calls. Pure
 * formatting of data the Top Risky Files table already has in hand.
 *
 * Deliberately honest about scope: this only covers the files that were
 * actually sampled and scored (see build-top-risky-files.ts's sampling
 * cap), not the entire repository. The header says so explicitly rather
 * than implying full coverage.
 */
/** GitHub usernames are alphanumeric + single hyphens only — no spaces. */
const VALID_GITHUB_USERNAME = /^[A-Za-z0-9-]+$/;

export function generateCodeownersContent(
  files: FileRiskEntry[],
  repoLabel: string
): string {
  const owned = files.filter(
    (file): file is FileRiskEntry & { owner: string } => file.owner !== null
  );
  const generatedAt = new Date().toISOString().slice(0, 10);

  const header = [
    "# CODEOWNERS — generated by Single Point",
    `# Repository: ${repoLabel}`,
    `# Generated: ${generatedAt}`,
    "#",
    `# These are the ${owned.length} highest-risk file(s) identified by`,
    "# knowledge-concentration analysis (bus factor, ownership",
    "# concentration, recency, and documentation coverage), listed here",
    "# most-concentrated-first.",
    "#",
    "# This is a PARTIAL file — it covers only the sampled highest-risk",
    "# files from this analysis, not the entire repository. Review and",
    "# expand before relying on it for real review routing.",
    "",
  ].join("\n");

  if (owned.length === 0) {
    return `${header}\n# No ownership data was available for the analyzed files.\n`;
  }

  const lines = [...owned]
    .sort((a, b) => b.riskScore - a.riskScore)
    .map((file) => {
      // Most contributors have a linked GitHub account, so `owner` is a
      // clean @username. Some commits are authored by a plain git name
      // with no linked account (e.g. "Matt Bierner") — that has a space
      // in it, which is invalid CODEOWNERS syntax (GitHub reads
      // everything after "@" up to the next whitespace as the username,
      // so "@Matt Bierner" would be misparsed as owner "@Matt" plus a
      // second, nonsensical path token "Bierner"). Rather than silently
      // dropping a genuinely risky file from the export, comment the
      // line out with an explanation instead.
      if (VALID_GITHUB_USERNAME.test(file.owner)) {
        return `${file.path}    @${file.owner}`;
      }
      return `# ${file.path}    (no linked GitHub account for "${file.owner}" — assign manually)`;
    });

  return `${header}${lines.join("\n")}\n`;
}